# Generated by Django 5.1.1 on 2025-01-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
