# Generated by Django 5.1.1 on 2025-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_profile_picture_user_referral_code_user_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=5),
        ),
    ]
