# Generated by Django 5.1.1 on 2025-06-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_webauthncredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='driver_license',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='national_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='proof_of_address',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
