# Generated by Django 5.1.1 on 2025-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_kyc_driver_license_alter_kyc_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
