# Generated by Django 5.1.1 on 2025-08-04 08:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_user_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['-updated_at'], 'verbose_name': 'KYC', 'verbose_name_plural': 'KYC Records'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at'], 'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='webauthncredential',
            options={'ordering': ['-registered_at'], 'verbose_name': 'WebAuthn Credential', 'verbose_name_plural': 'WebAuthn Credentials'},
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 8, 35, 51, 535023, tzinfo=datetime.timezone.utc), help_text='When the OTP expires'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kyc',
            name='bvn',
            field=models.CharField(blank=True, help_text='Bank Verification Number', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='driver_license',
            field=models.URLField(blank=True, help_text="URL to uploaded driver's license", null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='national_id',
            field=models.URLField(blank=True, help_text='URL to uploaded national ID document', null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='proof_of_address',
            field=models.URLField(blank=True, help_text='URL to proof of address document', null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', help_text='KYC verification status', max_length=10),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When KYC was last updated'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='user',
            field=models.OneToOneField(help_text='User associated with this KYC record', on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When KYC was verified', null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the OTP was created'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether the OTP has been used'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(help_text='The OTP code sent to the user', max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(help_text='User associated with this OTP', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the referral was created'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referer',
            field=models.ForeignKey(help_text='User who referred', on_delete=django.db.models.deletion.CASCADE, related_name='referral_referer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.ForeignKey(help_text='User who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referral_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Date the user joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="User's email address", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_busy',
            field=models.BooleanField(default=False, help_text='Is the user currently busy?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_service_provider',
            field=models.BooleanField(default=False, help_text='Is the user a service provider?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has the user completed KYC?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text="User's phone number", max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, help_text="User's PIN for additional security", max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='Profile picture URL', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text="User's referral code", max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(help_text="User's state of residence", max_length=50),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='credential_id',
            field=models.CharField(db_index=True, help_text='Identifier for the credential', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='When credential was last used', null=True),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='public_key',
            field=models.TextField(help_text='Base64URL encoded public key'),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When credential was registered'),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='sign_count',
            field=models.BigIntegerField(default=0, help_text='Counter to prevent replay attacks'),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='transports',
            field=models.CharField(blank=True, help_text="e.g., 'usb,nfc,ble,internal'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='user',
            field=models.ForeignKey(help_text='User associated with this credential', on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('user', 'referer')},
        ),
    ]
