# Generated by Django 5.1.1 on 2025-08-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_kyc_options_alter_otp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the OTP expires', null=True),
        ),
    ]
