# Generated by Django 5.1.1 on 2025-02-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_rename_requested_at_servicerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
