# Generated by Django 5.1.1 on 2025-02-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_service_max_price_alter_service_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Automobile', 'Automobile'), ('Carpentry', 'Carpentry'), ('Cleaning', 'Cleaning'), ('Plumbing', 'Plumbing'), ('Fumigation', 'Fumigation'), ('Legal', 'Legal'), ('Healthcare', 'Healthcare'), ('Fashion', 'Fashion'), ('Shopping', 'Shopping'), ('Construction', 'Construction'), ('Fitness', 'Fitness'), ('Engineering', 'Engineering'), ('Education', 'Education')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Automobile', 'Automobile'), ('Carpentry', 'Carpentry'), ('Cleaning', 'Cleaning'), ('Plumbing', 'Plumbing'), ('Fumigation', 'Fumigation'), ('Legal', 'Legal'), ('Healthcare', 'Healthcare'), ('Fashion', 'Fashion'), ('Shopping', 'Shopping'), ('Construction', 'Construction'), ('Fitness', 'Fitness'), ('Engineering', 'Engineering'), ('Education', 'Education')], max_length=100),
        ),
    ]
