# Generated by Django 5.1.1 on 2025-06-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_alter_service_category_alter_servicerequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
