# Generated by Django 5.1.1 on 2025-09-25 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0007_rename_provider_ap_busines_755927_idx_provider_ap_busines_75257d_idx'),
        ('service_app', '0007_alter_booking_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category (e.g., Electrical, Plumbing)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the category was last updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='service_app_service_4574ba_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='service_app_categor_83abb3_idx',
            old_name='service_app_categor_1149f8_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='service_app_categor_43b5dc_idx',
            old_name='service_app_categor_5919b9_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='bid',
            field=models.OneToOneField(default=1, help_text='The accepted bid for this booking', on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='service_app.servicerequestbid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(blank=True, help_text='Address of the service request location', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the service request location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the service request location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestbid',
            name='address',
            field=models.CharField(blank=True, help_text='Address of the bid location', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestbid',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the bid location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestbid',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the bid location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(help_text='Service provider handling the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='provider_app.serviceprovider'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='service_app_name_a5d073_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='service_app_is_acti_959a47_idx'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text='Category of the service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='service_app.category'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.ForeignKey(help_text='Category of the requested service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='service_app.category'),
        ),
    ]
