# Generated by Django 5.1.1 on 2025-01-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='avg_rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='closing_hour',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='company_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='company_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='company_phone_no',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='opening_hour',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='rating_population',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
