# Generated by Django 5.1.1 on 2025-02-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0002_remove_serviceprovider_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='closing_hour',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='opening_hour',
            field=models.CharField(max_length=10),
        ),
    ]
