# Generated by Django 5.1.1 on 2025-06-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0004_alter_serviceprovider_business_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
