# Generated by Django 5.1.1 on 2025-08-04 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0005_alter_serviceprovider_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Provider', 'verbose_name_plural': 'Service Providers'},
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average customer rating (0.00-5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='business_category',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Automobile', 'Automobile'), ('Carpentry', 'Carpentry'), ('Cleaning', 'Cleaning'), ('Plumbing', 'Plumbing'), ('Fumigation', 'Fumigation'), ('Legal', 'Legal'), ('Healthcare', 'Healthcare'), ('Fashion', 'Fashion'), ('Shopping', 'Shopping'), ('Construction', 'Construction'), ('Fitness', 'Fitness'), ('Engineering', 'Engineering'), ('Education', 'Education')], help_text='Business category/type', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='closing_hour',
            field=models.CharField(blank=True, help_text='Closing hour (e.g., 18:00)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='company_address',
            field=models.TextField(help_text='Physical address of the company'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='company_description',
            field=models.TextField(blank=True, help_text="Description of the company's services", null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='company_email',
            field=models.EmailField(help_text='Contact email address for the company', max_length=254),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='company_logo',
            field=models.URLField(blank=True, help_text="URL to the company's logo image", null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='company_name',
            field=models.CharField(help_text="Name of the service provider's company", max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='company_phone_no',
            field=models.CharField(help_text='Contact phone number for the company', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the provider profile was created'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the provider is approved by admin'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='opening_hour',
            field=models.CharField(blank=True, help_text='Opening hour (e.g., 08:00)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='rating_population',
            field=models.PositiveIntegerField(default=0, help_text='Number of ratings received'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(help_text='User account associated with this service provider', on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['business_category'], name='provider_ap_busines_755927_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_approved'], name='provider_ap_is_appr_80e762_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['avg_rating'], name='provider_ap_avg_rat_c7be76_idx'),
        ),
    ]
