# Generated by Django 5.1.1 on 2025-09-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0006_alter_serviceprovider_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serviceprovider',
            new_name='provider_ap_busines_75257d_idx',
            old_name='provider_ap_busines_755927_idx',
        ),
    ]
