# Generated by Django 5.1.1 on 2025-09-25 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0007_rename_provider_ap_busines_755927_idx_provider_ap_busines_75257d_idx'),
        ('service_app', '0008_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='business_category',
            field=models.ForeignKey(help_text='Business category/type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='service_app.category'),
        ),
    ]
